PUT https://rjtqxlhapj.execute-api.us-west-2.amazonaws.com/dev/tacos/recipes/481d33768b250fada990c6959c5c3e9b
Content-Type: application/json

{
    "name": "TacoMax - updated now",
    "description": "Best taco recipe today",
    "instructions": "slow cook",
    "ingredients": {
        "shell": "corn bread",
        "proteins": "8g",
        "toppings": "chili",
        "sauce": "tomato"
    }
}